config/routes.rb
SimpleToDo::Application.routes.draw do
  resources :tasks
  resources :lists
  devise_for :users

   root 'welcome#index'

end

app/models/controller.rb
class Controller < ActiveRecord::Base
end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, dependent: :destroy

	validates :name, presence: true, length: { maximum: 25 }
	validates :user_id, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :list

	validates :name, presence: true, length: { maximum: 60 }, uniqueness: true
	validates :completed, inclusion: { in: [true, false] }
	validates :list_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy
  has_many :tasks, through: :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/controllers_controller.rb
class ControllersController < ApplicationController
  before_action :set_controller, only: [:show, :edit, :update, :destroy]

  # GET /controllers
  # GET /controllers.json
  def index
    @controllers = Controller.all
  end

  # GET /controllers/1
  # GET /controllers/1.json
  def show
  end

  # GET /controllers/new
  def new
    @controller = Controller.new
  end

  # GET /controllers/1/edit
  def edit
  end

  # POST /controllers
  # POST /controllers.json
  def create
    @controller = Controller.new(controller_params)

    respond_to do |format|
      if @controller.save
        format.html { redirect_to @controller, notice: 'Controller was successfully created.' }
        format.json { render action: 'show', status: :created, location: @controller }
      else
        format.html { render action: 'new' }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controllers/1
  # PATCH/PUT /controllers/1.json
  def update
    respond_to do |format|
      if @controller.update(controller_params)
        format.html { redirect_to @controller, notice: 'Controller was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controllers/1
  # DELETE /controllers/1.json
  def destroy
    @controller.destroy
    respond_to do |format|
      format.html { redirect_to controllers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_controller
      @controller = Controller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def controller_params
      params.require(:controller).permit(:Tasks)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = current_user.lists
  end

  def new
    @list = current_user.lists.build
  end

  def create
    @list = current_user.lists.build(list_params)

    if @list.save
      flash[:success] = "List created successfully!"
      redirect_to @list
    else
      flash[:danger] = "There was an error saving the list, please try again"
      render 'new'
    end
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update_attributes(list_params)
      flash[:success] = "List renamed successfully"
      redirect_to @list
    else
      render 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])

    if @list.present?
      @list.destroy
      flash[:success] = "List deleted successfully!"
    end

    redirect_to lists_path
  end

  # Custom Methods

  def share
  end

  private
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		@tasks = current_user.tasks
	end
	
	def new
		@task = current_user.tasks.build
		@lists = current_user.lists
	end

	def create
		@task = current_user.tasks.build(task_params)

		if @task.save
			flash[:success] = "Task created successfully!"
			redirect_to @task
		else
			flash[:danger] = "There was an error, please try again"
			render 'new'
		end
	end

	def show
		@task = Task.find(params[:id])
	end

	def edit
		@task = Task.find(params[:id])
		@lists = current_user.lists
	end

	def update
		@task = Task.find(params[:id])

		if @task.update_attributes(task_params)
			flash[:success] = "Task updated successfully!"
			redirect_to @task
		else
			flash[:danger] = "There was an error, please try again"
			render 'edit'
		end 
	end

	def destroy
		@task = Task.find(params[:id])

		if @task.present?
			@task.destroy
			flash[:success] = "Task deleted successfully!"
		end

		redirect_to root_path
	end
end

private
		def task_params
			params.require(:task).permit(:name, :completed, :list_id)
		end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/controllers/_form.html.erb
<%= form_for(@controller, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @controller.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@controller.errors.count, "error") %> prohibited this controller from being saved:</h4>

      <ul>
      <% @controller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Tasks, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :Tasks, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/controllers/edit.html.erb
<div class="page-header">
  <%= link_to controllers_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @controller, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing controller</h1>
</div>

<%= render 'form' %>

app/views/controllers/index.html.erb
<div class="page-header">
  <%= link_to new_controller_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Controller
  <% end %>
  <h1>Listing controllers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Tasks</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @controllers) do |controller| %>
            <td><%= controller.Tasks %></td>
            <td><%= link_to 'Show', controller %></td>
        <td><%= link_to 'Edit', edit_controller_path(controller) %></td>
        <td><%= link_to 'Destroy', controller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/controllers/new.html.erb
<div class="page-header">
  <%= link_to controllers_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New controller</h1>
</div>

<%= render 'form' %>

app/views/controllers/show.html.erb
<div class="page-header">
  <%= link_to controllers_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_controller_path(@controller), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show controller</h1>
</div>

<dl class="dl-horizontal">
  <dt>Tasks:</dt>
  <dd><%= @controller.Tasks %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Simple To Do</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Simple To Do", root_path, :class => "navbar-brand" %>
      </div>

      <!--Left Navbar Menu -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <!--Lists-->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Lists<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'View All Lists', lists_path %></li>
                <li><%= link_to 'Create a New List', new_list_path %></li>
                <li><a href="#">Email a List</a></li>
              </ul>
            </li>
            <!--Tasks-->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Tasks<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Create a new Task", new_task_path %></li>
                <li><%= link_to "View all of my tasks", tasks_path %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      

      <!-- Right Navbar Menu -->
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><p class="navbar-text">Hello <%= current_user.email %></p></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: "delete" %></li>
            <li><%= link_to 'Settings', root_path %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><%= link_to 'Register a new Account', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list, html: {class: 'form-horizontal' }) do |f| %>
	<%= f.input :name, label: 'List Name' %>
	<div class="col-lg-2"></div><%= f.button :submit %>
<% end %>

app/views/lists/create.html.erb
<div class="page-header">
  <h1>List#create</h1>
</div>
<p>Find me in app/views/list/create.html.erb</p>

app/views/lists/destroy.html.erb
<div class="page-header">
  <h1>List#destroy</h1>
</div>
<p>Find me in app/views/list/destroy.html.erb</p>

app/views/lists/edit.html.erb
<div class="page-header">
  <h1>Rename this List</h1>
</div>

<%= render 'form' %>

app/views/lists/index.html.erb
<div class="page-header">
  <h1>Your Lists</h1>
  <h3><i>You have <%= pluralize(@lists.count, 'list') %></i></h3>
</div>

<table class="table">
	<tr>
		<th>List</th>
		<th>Tasks</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>

	<% @lists.each do |list| %>
		<tr>
			<td><%= link_to list.name, list %></td>
			<td><%= list.tasks.count %></td>
			<td><%= link_to "Edit", edit_list_path(list) %></td>
			<td><%= link_to "Delete", list, method: :delete, data: { confirm: "Are you sure? You cannot undo this action" } %></td>
		</tr>
	<% end %>
</table>

app/views/lists/new.html.erb
<div class="page-header">
  <h1>Create a new List</h1>
</div>

<%= render 'form' %>

app/views/lists/share.html.erb
<div class="page-header">
  <h1>Email a List</h1>
</div>
<p>Find me in app/views/list/share.html.erb</p>

app/views/lists/show.html.erb
<div class="page-header">
  <h1><%= @list.name %></h1>
  <h3><%= link_to "Rename this List", edit_list_path(@list) %> | <%= link_to "Delete this list", @list, method: :delete, data: { confirm: "Are you sure?" } %> | <%= link_to "Add a task", new_task_path(list: @list) %></h3>
</div>

<% if @list.tasks.any? %>
	<table class="table">
		<tr>
			<th>Task</th>
			<th>Completed?</th>
		</tr>

		<% @list.tasks.each do |task| %>
			<tr>
				<td><%= task.name %></td>
				<td><%= task.completed %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<h4>You have no tasks yet, would you like to <%= link_to "add one?", new_task_path %></h4>
<% end %>

app/views/lists/update.html.erb
<div class="page-header">
  <h1>List#update</h1>
</div>
<p>Find me in app/views/list/update.html.erb</p>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: {class: 'form-horizontal' }) do |f| %>
	<%= f.input :name, label: 'Task Name' %>
	<%= f.input :completed, label: 'Completed?' %>
  	<%= f.input :list_id, collection: @lists, group_method: :name %>
	<div class="col-lg-2"></div><%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>Update this Task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <h1>Your Tasks</h1>
  <h3><i>You have <%= pluralize(@tasks.count, 'task') %></i></h3>
</div>

<table class="table">
	<tr>
		<th>Task</th>
		<th>List<th>
		<th>Completed?</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>

	<% @tasks.each do |task| %>
		<tr>
			<td><%= task.name %></td>
			<td><%= task.list.name %></td>
			<td><%= task.completed %></td>
			<td><%= link_to "Edit", edit_task_path(task) %></td>
			<td><%= link_to "Delete", task, method: :delete, data: { confirm: "Are you sure? You cannot undo this action" } %></td>
		</tr>
	<% end %>
</table>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1> 
  	<% if @list %>
  		Add a new Task to <%= @list.name %>
  	<% else %>
  		Create a new task
  	<% end %>
  </h1>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <h1><%= @task.name %></h1>
  <h3><%= link_to "Rename this Task", edit_task_path(@task) %> | <%= link_to "Delete this task", @task, method: :delete, data: { confirm: "Are you sure?" } %></h3>
</div>

Name: <%= @task.name %><br>
Completed?: <%= @task.completed %><br>
List: <%= @task.list.name %><br>

app/views/welcome/index.html.erb
<div class="page-header">
	<h1>Simple To Do</h1>
	<h3>A test driven rails app using Devise, RSpec and Bootstrap</h3>
</div>

<div class="row">
	<div class="col-lg-6">
		<h4>
			<ul>
				<li>Create and manage multiple task lists</li>
				<li>Add and manage individual tasks</li>
				<li>Search and sort lists and tasks</li>
				<li>Share your list with friends</li>
			</ul>
		</h4>
	</div>


	<div class="col-lg-6">
		<h3>Want to take a sneak peak? Just log in with the example guest user...</h3>
		<h4>Email Address: <i>guest@example.com</i></h4>
		<h4>Password: <i>guestuser</i></h4>
	</div>
</div>